channels:
    - conda-forge
dependencies:
    - python=3.*
    # PySR/
    - julia <=1.7.1
    - pyjulia >= 0.5.7
    - openlibm <0.8.0
    - numpy >=1.14.0
    - scikit-learn
    - sympy
    - pandas
    # /PySR
    - pyyaml
    - pip
    - pip:
        - git+https://github.com/MilesCranmer/PySR.git@4af4af74127216bd93bf5547f00a03bcc2dbbd91