name: nsga-dcgp
channels:
    - conda-forge
dependencies:
    - python=3.9.5
    - pytorch=1.8.1
    - numpy=1.21.0
    - pandas=1.1.*
    - scikit-learn=0.24.2
    - sympy=1.8
    - pip
    - pip:
        - pandas==1.3.0
        - pmlb===1.*
