# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SRBench
subtitle: A living benchmark for symbolic regression
# email: william.lacava@childrens.harvard.edu 
description: >- # this means to ignore newlines until "baseurl:"
  A living benchmark for symbolic regression
# twitter_username: w_la_cava
github_username:  cavalab
repository: "cavalab/srbench"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin:  "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

domain: srbench.cavalab.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cavalab.org/srbench  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: "/srbench"      # place folder name if the site is served in a subfolder

# breadcrumbs: true

defaults:
  # _docs
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main"
      layout: single
      toc: true
      author_profile: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cavalab/srbench/"
    - label: "Cavalab"
      # icon: "fab fa-fw fa-ruler-combined" # doesn't work
      icon: "fas fa-microscope" 
      # icon: "fas fa-fw fa-link"
      url: "https://cavalab.org"

author:
  bio: "Maintained by [@cavalab](https://github.com/cavalab) and many open-source contributors"
  links:
    - label: "GitHub Repo"
      icon: "fab fa-fw fa-github"
      # icon: "fa-light fa-chart-network" # doesn't work
      url: "https://github.com/cavalab/srbench"

atom_feed:
  hide: true
