name: gecco-comp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - setuptools=75.1.0
  - pip=24.2
  - dill=0.3.9
  - lark==1.2.2
  - loguru==0.7.2
  - lark==1.2.2
  - loguru==0.7.2
  - numpy==2.1.1
  - palettable==3.3.3
  - pandas==2.2.3
  - pathos==0.3.3
  - polyleven==0.8
  - pytest==8.3.3
  - pytest-benchmark==4.0.0
  - scikit-learn==1.5.2
  - seaborn==0.13.2
  - sympy==1.13.3
  - threadpoolctl==3.5.0
  - z3-solver==4.13.2.0
  - pip:
      - geneticengine @ git+https://github.com/alcides/GeneticEngine.git@693bf09f861402d2c031e021e3d17cb2b71a1dd1
