name: gecco-comp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - setuptools=75.1.0
  - pip=24.2
  - pip:
      - geneticengine @ git+https://github.com/alcides/GeneticEngine.git@0054d747515740771fc50f1ab7a0a914734730e7
