name: gecco-comp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - setuptools=75.1.0
  - pip=24.2
  - dill=0.3.9
  - pip:
      - geneticengine @ git+https://github.com/alcides/GeneticEngine.git@ec0a632943245144b241011874ccf516b2309e08
