name: gecco-comp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - setuptools=75.1.0
  - pip=24.2
  - dill=0.3.9
  - pip:
      - geneticengine @ git+https://github.com/alcides/GeneticEngine.git@5e7c4ec8807b8299f92e0347443714e16f22e40f
