# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - Competition2022
    # paths:
    #   - 'submission/**'
    # paths-ignore:
    #   - 'submission/example/**'
  pull_request:
    branches: 
      - Competition2022 
    # paths:
    #   - 'submission/**'
    # paths-ignore:
    #   - 'submission/example/**'

env: 
  CACHE_NUMBER: 0

jobs:
  ################################################################################
  # environment setup
  ################################################################################
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: srcomp
          use-mamba: true
      - 
        name: Cache conda
        uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/srcomp
          # key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml')}}-${{ github.sha }}
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
        id: cache
      - 
        name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: | 
          mamba env update -n srcomp -f environment.yml 
          mamba env export
################################################################################
# install the submission
################################################################################
      - 
        name: get new folder name
        id: get-folder
        run: |
          ls
          echo "$(ls -t submission/ | head -n 1)"
          echo "::set-output name=folder::$( ls -t submission/ | head -n 1 )"
      # - 
      #   name: get submission metadata 
      #   id: metadata
      #   run: |
      #     folder=$(ls -t submission/ | head -n 1)
      #     echo $folder
      #     echo '::set-output name=folder::${folder}'
      - 
        name: Install SR dependencies
        env:
          folder: ${{ steps.get-folder.outputs.folder }} 
          # submission_name: ${{ steps.get-metadata.outputs.name }}
        if: hashFiles('${{ env.folder }}/environment.yml') != ''
        run: |
          cd "submission/${{ env.folder }}"
          echo "Installing dependencies for ${{ env.folder }}"
          echo "Copying base environment"
          conda create --name srcomp-submission --clone srcomp
          echo "Installing conda dependencies"
          mamba env update -n srcomp-submission -f environment.yml
      - 
        name: Install SR method
        env:
          folder: submission/${{ steps.get-folder.outputs.folder }} 
        if: hashFiles('${{ env.folder }}/install.sh') != ''
        run: |
          pwd
          ls
          cd ${{ env.folder }} 
          echo "running install.sh..."
          mamba run -n srcomp-submission bash install.sh
          # pwd
          # echo "Installing ${{ env.submission_name }}"
          # echo "Copying base environment"
          # envname="srcomp-${env.submission_name}" 
          # conda create --name "${envname}" --clone srcomp
          # echo "Installing conda dependencies"
          # mamba env update -n "${envname}" -f environment.yml
      - name: Copy files
        env:
          folder: submission/${{ steps.get-folder.outputs.folder }} 
        run: |
          cp -R ${{ env.folder}} experiment/methods/
  ################################################################################
  # tests
  ################################################################################
      - 
        name: Test Method
        env:
          folder: submission/${{ steps.get-folder.outputs.folder }} 
        run: |
          pwd
          ls
          cd experiment
          conda env list
          conda info
          mamba run -n srcomp-submission python -m pytest -v test_evaluate_model.py --ml ${{ env.folder }}
