# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7.1']
        os: [ubuntu-latest]
        algorithm: ["AFPRegressor", "AIFeynman", "BSRRegressor", "DSRRegressor", "EHCRegressor", "FFXRegressor", "FEATRegressor", "FE_AFPRegressor", "EPLEXRegressor", "GPGOMEARegressor", "gplearn", "ITEARegressor", "MRGPRegressor", "OperonRegressor", "PySRRegressor", "sembackpropgp"]
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda Environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: srbench
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
          conda activate srbench

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1.6.0
        with:
          version: ${{ matrix.julia-version }}

      - name: "Change julia package server"
        shell: bash
        env:
            JULIA_PKG_SERVER: ""
        run: julia -e 'using Pkg; Pkg.Registry.add("General")'

      # TODO: Only install algorithm required.
      - name: Install SR methods
        run: |
            conda info
            bash install.sh
      
      - name: Test analysis 
        run: |
            conda info 
            # pip install pytest
            cd experiment
            python -m pytest -v test_evaluate_model.py ${{ matrix.algorithm }}
            python -m pytest -v test_tuned_models.py ${{ matrix.algorithm }}
